/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica2;

import static com.mycompany.practica2.AlmacenDatos.getAlmacenDatos;
import static com.mycompany.practica2.GraficaBarras.n1;
import static com.mycompany.practica2.GraficaBarras.nombreGraf;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtils;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author marroquin
 */
public class MiInicio extends javax.swing.JFrame {

    public static boolean estado = true;
    public static String vel;
    public static String tip;
    public static String alg;
    private JFreeChart grafico_Barras;
    public static String notas1="";
    public static String cursos1="";

    /**
     * Creates new form MiInicio
     */
    public MiInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreGrafica = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RutaArchivo = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        BotonCargar = new javax.swing.JButton();
        PanelOpcionesText = new javax.swing.JLabel();
        GraficaText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AlgoritmoText = new javax.swing.JLabel();
        AlgoritmoCaja = new javax.swing.JComboBox<>();
        TipoText = new javax.swing.JLabel();
        TipoCaja = new javax.swing.JComboBox<>();
        VelocidadText = new javax.swing.JLabel();
        VelocidadCaja = new javax.swing.JComboBox<>();
        BotonEjecutar = new javax.swing.JButton();
        panelGrafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica2");
        setResizable(false);

        jLabel1.setText("Ruta del Archivo");

        NombreGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreGraficaActionPerformed(evt);
            }
        });

        jLabel2.setText("Título de la gráfica");

        RutaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaArchivoActionPerformed(evt);
            }
        });

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonCargar.setText("Cargar");
        BotonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarActionPerformed(evt);
            }
        });

        PanelOpcionesText.setText("Panel de Opciones");

        GraficaText.setText("Gráfica");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        AlgoritmoText.setText("Algoritmo");

        AlgoritmoCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burbuja", "Seleccion", "Insercion" }));
        AlgoritmoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgoritmoCajaActionPerformed(evt);
            }
        });

        TipoText.setText("Tipo");

        TipoCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));
        TipoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCajaActionPerformed(evt);
            }
        });

        VelocidadText.setText("Velocidad");

        VelocidadCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Rapida" }));
        VelocidadCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadCajaActionPerformed(evt);
            }
        });

        BotonEjecutar.setText("Ejecutar");
        BotonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEjecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AlgoritmoText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AlgoritmoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(VelocidadText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VelocidadCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TipoText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BotonEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlgoritmoText)
                    .addComponent(AlgoritmoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoText)
                    .addComponent(TipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VelocidadText)
                    .addComponent(VelocidadCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(BotonEjecutar)
                .addGap(17, 17, 17))
        );

        panelGrafica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RutaArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                                    .addComponent(NombreGrafica))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelOpcionesText)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GraficaText))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscar))
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCargar))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanelOpcionesText)
                    .addComponent(GraficaText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEjecutarActionPerformed
        this.dispose();
        Ejecutar ejecutar = new Ejecutar();
        ReporteHTML reporte = new ReporteHTML();
        ejecutar.setVisible(true);
        ejecutar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        estado = true;
        ejecutar.tiempo1();
        ejecutar.caracteristicas();
       if(alg.equals("Burbuja") && tip.equals("Ascendente")){
            RecibirCsv.bur();
            ejecutar.burbuja();
            //reporte.prueba1();
            
        }
        
        if(alg.equals("Burbuja") && tip.equals("Descendente")){
           RecibirCsv.burDes();
           ejecutar.burbuja();
           //reporte.prueba1();
        }
        
        if(alg.equals("Seleccion")&& tip.equals("Ascendente")){
            RecibirCsv.seleccion();
            ejecutar.burbuja();
            //reporte.prueba1();
        }
        
        if(alg.equals("Seleccion")&& tip.equals("Descendente")){
            RecibirCsv.seleccionDes();
            ejecutar.burbuja();
            //reporte.prueba1();
        }
        
        if(alg.equals("Insercion")&& tip.equals("Ascendente")){
            RecibirCsv.insercion();
            ejecutar.burbuja();
            //reporte.prueba1();
        }
                
        if(alg.equals("Insercion")&& tip.equals("Descendente")){
            RecibirCsv.insercionDes();
            ejecutar.burbuja();
            //reporte.prueba1();
        }
        
        
        
        
        
        
        
        

    }//GEN-LAST:event_BotonEjecutarActionPerformed

    private void TipoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCajaActionPerformed
        String tipo;
        tip = (String)TipoCaja.getSelectedItem();
        
    }//GEN-LAST:event_TipoCajaActionPerformed

    private void AlgoritmoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgoritmoCajaActionPerformed
        String algoritmo;
        alg = (String)AlgoritmoCaja.getSelectedItem();
        
    }//GEN-LAST:event_AlgoritmoCajaActionPerformed

       
        
    private void BotonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarActionPerformed
        GraficaBarras.TituloGrafica(NombreGrafica.getText());

        DefaultCategoryDataset datos = new DefaultCategoryDataset();

        for (datos dato : getAlmacenDatos()) {
            if (dato != null) {

                int numero1 = dato.getNotas();
                String numero2 =String.valueOf(numero1);
                datos.setValue(numero1, dato.getCursos(),"");
                notas1+="<th>"+numero2+"</th>";
                cursos1+="<th>"+dato.getCursos()+"</th>";

            }

        }

        grafico_Barras = ChartFactory.createBarChart(NombreGrafica.getText(), AlmacenDatos.encabezado1, AlmacenDatos.encabezado2, datos, PlotOrientation.VERTICAL, true, true, false);
        //JFreeChart grafico_Barras = ChartFactory.createBarChart(nombreGraf, nombreGraf, nombreGraf, datos, PlotOrientation.HORIZONTAL, rootPaneCheckingEnabled, rootPaneCheckingEnabled, rootPaneCheckingEnabled)
        ChartPanel panel = new ChartPanel(grafico_Barras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(546, 237));
        panelGrafica.setLayout(new BorderLayout());

        panelGrafica.add(panel, BorderLayout.NORTH);

        pack();
        repaint();
        generarImg1();
    }//GEN-LAST:event_BotonCargarActionPerformed

     public String CursosEstadoInicial(){
     return cursos1;
 }
        
 
  public String NotasEstadoInicial(){
     return notas1;
    }
    
    
    
    
    
    
    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        if (archivo != null) {
            RutaArchivo.setText(archivo.getAbsolutePath());
            RecibirCsv.recibir(archivo.getAbsolutePath());
            //RecibirCsv.bur();
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void RutaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaArchivoActionPerformed
        String rutaArc;
        rutaArc = RutaArchivo.getText();
    }//GEN-LAST:event_RutaArchivoActionPerformed

    private void NombreGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreGraficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreGraficaActionPerformed

    private void VelocidadCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadCajaActionPerformed
        String velocidad;
        vel = (String)VelocidadCaja.getSelectedItem();
        
        
        
    }//GEN-LAST:event_VelocidadCajaActionPerformed

    public void generarImg1(){
    try{
        final File file = new File("grafica1.png");
        ChartUtils.saveChartAsPNG(file, grafico_Barras, 800,  400);
        //this.dispose();
        
    }catch(IOException e){
        System.out.println("Erro en la img");
    } 
    }
    
    public String sendVelocidad() {
        return vel;
    }

    public String sendAlgoritmo() {
        return alg;
    }

    public String sendTipo() {
        return tip;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MiInicio.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MiInicio.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MiInicio.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MiInicio.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MiInicio().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlgoritmoCaja;
    private javax.swing.JLabel AlgoritmoText;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonCargar;
    private javax.swing.JButton BotonEjecutar;
    private javax.swing.JLabel GraficaText;
    private javax.swing.JTextField NombreGrafica;
    private javax.swing.JLabel PanelOpcionesText;
    private javax.swing.JTextField RutaArchivo;
    private javax.swing.JComboBox<String> TipoCaja;
    private javax.swing.JLabel TipoText;
    private javax.swing.JComboBox<String> VelocidadCaja;
    private javax.swing.JLabel VelocidadText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelGrafica;
    // End of variables declaration//GEN-END:variables
}
